colo desert
set nocp
set ff=unix
set enc=utf-8
set fenc=utf-8
set ambw=double
"indent
set bs=2
set cin
set si
set sw=2
set ts=2
set et
"look
set nu
set ru
"search
set is
set hls
set hid
set acd
set ic
set scs
"fold
set fen
set fdm=syntax
set fdl=100

"status bar
set ls=2
set stl=%<%F%m\ \[%{&ff}:%{&fenc}:%Y%{&bomb?'\:BOM':''}]\ \ \[%{strftime('%Y%e%d\ %a\ %H:%M')}\]\ %=\ Row:%l\/%L\(%p%%)\ Col:%c%V\ %P

set so=3
set sm
set cul
set cuc
"patch for theme desert
au ColorScheme desert hi CursorLine ctermfg=NONE ctermbg=black cterm=NONE
au ColorScheme desert hi CursorColumn ctermfg=NONE ctermbg=black cterm=NONE
"bak
set wb
set nobk
set hi=50
set mouse=a
syn on
set list lcs=tab:..,eol:$
filetype plugin indent on
au BufRead,BufNewFile *.cpp,*,cc,*.c,*.h,*.hh,*.hpp,*.py,*.php,*.rb,*.js,*.node,*.sh,*.vim,*.css 2match Underlined /.\%81v/
if has("gui_running")
  set lines=35 columns=120
  "set guioptions-=m
  set guioptions-=T
endif

"pair
:ino ( ()<esc>i
:ino ) <c-r>=ClosePair(')')<cr>
:ino { {}<esc>i
:ino } <c-r>=ClosePair('}')<cr>
:ino [ []<esc>i
:ino ] <c-r>=ClosePair(']')<cr>
:ino " ""<esc>i
:ino ' ''<esc>i
fu! ClosePair(char)
  if getline('.')[col('.') - 1] == a:char
    return "\<Right>"
  else
    return a:char
  endif
endf
"auto complete
"insert mode only
"tags
ino <c-]> <c-X><c-]>
"filename
ino <c-f> <c-X><c-f>
"macro
ino <c-d> <c-X><c-d>
"header file
ino <c-i> <c-X><c-i>

"esc
ino jk <esc>
ino <esc> <nop>
vn jk <esc>
vn <esc> <nop>

"header macro c/cpp
fu! s:insert_gates()
  let gatename = substitute(toupper(expand("%:t")), "\\.", "_", "g")
  exe "norm! i#ifndef " . gatename
  exe "norm! o#define " . gatename . " "
  exe "norm! Go#endif /* " . gatename . " */"
  normal! kk
endf
au BufNewFile *.{h,hh,hpp} call <SID>insert_gates()

"highlight search off
nn <esc><esc> <esc>:nohl<cr><esc>
vn <esc><esc> <esc>:nohl<cr><esc>

"root using w!! command
cm w!! w !sudo tee > /dev/null %

"vim-plug instead of vundle
"call plug#begin('~/.vim/plugged')
"Plug 'dyng/ctrlsf.vim'
"Plug 'octol/vim-cpp-enhanced-highlight'
"Plug 'skywind3000/asyncrun.vim'
"call plug#end()
